baseURL = "http://example.com/"
languageCode = "en-us"
title = "aeronautical"
theme = "hugograyscale"
#googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    # Provide some metadata for search and indexing services
    description = "A port of the Grayscale theme to Hugo"

[Author]
    name = "mario carpeggiani"
    email = "mario@aeronautical.com.au"

[Social]
    linkein = "carpeggiani"
